### ISSUE TITLE
v

### ISSUE THREAD

**Issue by chocolatemoo53** [LS3solutions/openstream-server#20]

**Comment by mirh** [comment]
That's normal, Secure Desktop is supposed to be isolated from any other process. 

GFE and steam solves it by way of a custom HID driver (so input isn't "simulated", but it appears like a legit input device).. even though I'm not really sure if the screen still get streamed (it's [somehow](https://stackoverflow.com/a/52646121/5994170) possible.. hell, maybe GFE even has a preferential access to the screen framebuffer, but it's really hairy)

**Comment by rionthedeveloper** [comment]
You're correct @mirh

This was just a problem I saw on two different places so I was adding it in case it was going to be fixed or not. 

Also, since this is the full desktop, not just games, people will get UAC prompts all the time. If it could be fixed, it would be helpful.
